---
title: "ACTS 135 - Mathematical Statistics"
author: "Linfeng Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a digital book that contains all learning materials related to ACTS 135 - Mathematical Statistics"
---

# About This Course

This course is developed based on *Mathematical Statistics*, 7th Edition (2008), Wackerly, Mendenhall, and Scheaffer.

This course is an introduction to the basic principles of mathematical statistics, and is a companion course to ACTS 131, which focused more on probability. In fact, we use the same textbook here (Chapters 8-10, 14-15) as was used for ACTS 131 (Chapters 1-7). This course provides credit for the VEE (Validation by Educational Experience) requirement of the SOA for Mathematical Statistics, provided a student receives a grade of B- or above.  If on the CAS track, it relates to the Statistics portion of Exam MAS-I.

The course is divided into four chunks as follows:

* Chapter 8: Point and Interval Estimation of Model Parameters
* Chapter 9: Properties of Estimators and Methods of Estimation
* Chapter 10: Hypothesis Testing for Mean, Variance, and Proportion Parameters
* Chapters 14-15: Selected Tests for Categorical Data and Nonparametric Statistics
